src/main/java/org/agoncal/application/petstore/domain/CartItem.java
package org.agoncal.application.petstore.domain;

import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * @author Antonio Goncalves
 *         http://www.antoniogoncalves.org
 *         --
 */

public class CartItem {

    // ======================================
    // =             Attributes             =
    // ======================================

    @NotNull
    private Item item;
    @NotNull
    @Min(1)
    private Integer quantity;

    // ======================================
    // =            Constructors            =
    // ======================================

    public CartItem(Item item, Integer quantity) {
        this.item = item;
        this.quantity = quantity;
    }

    // ======================================
    // =              Public Methods        =
    // ======================================

    public Float getSubTotal() {
        return item.getUnitCost() * quantity;
    }

    // ======================================
    // =         Getters & setters          =
    // ======================================

    public Item getItem() {
        return item;
    }

    public void setItem(Item item) {
        this.item = item;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    // ======================================
    // =   Methods hash, equals, toString   =
    // ======================================


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        CartItem cartItem = (CartItem) o;

        if (!item.equals(cartItem.item)) return false;
        if (!quantity.equals(cartItem.quantity)) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = item.hashCode();
        result = 31 * result + quantity.hashCode();
        return result;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder();
        sb.append("CartItem");
        sb.append("{item='").append(item).append('\'');
        sb.append(", quantity='").append(quantity).append('\'');
        sb.append('}');
        return sb.toString();
    }
}

src/main/java/org/agoncal/application/petstore/domain/CreditCardType.java
package org.agoncal.application.petstore.domain;

/**
 * @author Antonio Goncalves
 *         http://www.antoniogoncalves.org
 *         --
 */

public enum CreditCardType {

    // ======================================
    // =             Constants              =
    // ======================================

    VISA,
    MASTER_CARD,
    AMERICAN_EXPRESS
}

src/main/java/org/agoncal/application/petstore/web/AccountController.java
package org.agoncal.application.petstore.web;

import org.agoncal.application.petstore.domain.Customer;
import org.agoncal.application.petstore.service.CustomerService;
import org.agoncal.application.petstore.util.Loggable;

import javax.enterprise.context.Conversation;
import javax.enterprise.context.SessionScoped;
import javax.enterprise.inject.Produces;
import javax.inject.Inject;
import javax.inject.Named;
import javax.security.auth.login.LoginContext;
import javax.security.auth.login.LoginException;
import java.io.Serializable;

/**
 * @author Antonio Goncalves
 *         http://www.antoniogoncalves.org
 *         --
 */

@Named
@SessionScoped
@Loggable
@CatchException
public class AccountController extends Controller implements Serializable {

    // ======================================
    // =             Attributes             =
    // ======================================

    @Inject
    private CustomerService customerService;

    @Inject
    private Credentials credentials;

    @Inject
    private Conversation conversation;

    @Produces
    @LoggedIn
    private Customer loggedinCustomer;

    @Inject
    @SessionScoped
    private transient LoginContext loginContext;

    // ======================================
    // =              Public Methods        =
    // ======================================

    public String doLogin() throws LoginException {
        if ("".equals(credentials.getLogin())) {
            addWarningMessage("id_filled");
            return null;
        }
        if ("".equals(credentials.getPassword())) {
            addWarningMessage("pwd_filled");
            return null;
        }

        loginContext.login();
        loggedinCustomer = customerService.findCustomer(credentials.getLogin());
        return "main.faces";
    }

    public String doCreateNewAccount() {

        // Login has to be unique
        if (customerService.doesLoginAlreadyExist(credentials.getLogin())) {
            addWarningMessage("login_exists");
            return null;
        }

        // Id and password must be filled
        if ("".equals(credentials.getLogin()) || "".equals(credentials.getPassword()) || "".equals(credentials.getPassword2())) {
            addWarningMessage("id_pwd_filled");
            return null;
        } else if (!credentials.getPassword().equals(credentials.getPassword2())) {
            addWarningMessage("both_pwd_same");
            return null;
        }

        // Login and password are ok
        loggedinCustomer = new Customer();
        loggedinCustomer.setLogin(credentials.getLogin());
        loggedinCustomer.setPassword(credentials.getPassword());

        return "createaccount.faces";
    }

    public String doCreateCustomer() {
        loggedinCustomer = customerService.createCustomer(loggedinCustomer);
        return "main.faces";
    }


    public String doLogout() {
        loggedinCustomer = null;
        // Stop conversation
        if (!conversation.isTransient()) {
            conversation.end();
        }
        addInformationMessage("been_loggedout");
        return "main.faces";
    }

    public String doUpdateAccount() {
        loggedinCustomer = customerService.updateCustomer(loggedinCustomer);
        addInformationMessage("account_updated");
        return "showaccount.faces";
    }

    public boolean isLoggedIn() {
        return loggedinCustomer != null;
    }

    public Customer getLoggedinCustomer() {
        return loggedinCustomer;
    }

    public void setLoggedinCustomer(Customer loggedinCustomer) {
        this.loggedinCustomer = loggedinCustomer;
    }
}

src/main/java/org/agoncal/application/petstore/web/CatalogController.java
package org.agoncal.application.petstore.web;

import org.agoncal.application.petstore.domain.Item;
import org.agoncal.application.petstore.domain.Product;
import org.agoncal.application.petstore.service.CatalogService;
import org.agoncal.application.petstore.util.Loggable;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.util.List;

/**
 * @author Antonio Goncalves
 *         http://www.antoniogoncalves.org
 *         --
 */

@Named
//@RequestScoped TODO should be request scoped
@SessionScoped
@Loggable
@CatchException
public class CatalogController extends Controller implements Serializable {

    // ======================================
    // =             Attributes             =
    // ======================================

    @Inject
    private CatalogService catalogService;

    private String categoryName;
    private Long productId;
    private Long itemId;

    private String keyword;
    private Product product;
    private Item item;
    private List<Product> products;
    private List<Item> items;

    // ======================================
    // =              Public Methods        =
    // ======================================

    public String doFindProducts() {
        products = catalogService.findProducts(categoryName);
        return "showproducts.faces";
    }

    public String doFindItems() {
        product = catalogService.findProduct(productId);
        items = catalogService.findItems(productId);
        return "showitems.faces";
    }

    public String doFindItem() {
        item = catalogService.findItem(itemId);
        return "showitem.faces";
    }

    public String doSearch() {
        items = catalogService.searchItems(keyword);
        return "searchresult.faces?keyword=" + keyword + "&faces-redirect=true";
    }

    // ======================================
    // =         Getters & setters          =
    // ======================================

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public Item getItem() {
        return item;
    }

    public void setItem(Item item) {
        this.item = item;
    }

    public List<Product> getProducts() {
        return products;
    }

    public List<Item> getItems() {
        return items;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public Long getItemId() {
        return itemId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }
}

src/main/java/org/agoncal/application/petstore/web/Controller.java
package org.agoncal.application.petstore.web;

import org.agoncal.application.petstore.util.Loggable;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import java.text.MessageFormat;
import java.util.Locale;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.logging.Logger;

/**
 * @author Antonio Goncalves
 *         http://www.antoniogoncalves.org
 *         --
 */

@Loggable
abstract class Controller {

    // ======================================
    // =             Attributes             =
    // ======================================

    @Inject
    private transient Logger logger;

    // ======================================
    // =          Protected Methods         =
    // ======================================

    private String getMessage(FacesContext facesContext, String msgKey, Object... args) {
        Locale locale = facesContext.getViewRoot().getLocale();
        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        ResourceBundle bundle = ResourceBundle.getBundle("messages", locale, classLoader);
        String msgValue = bundle.getString(msgKey);
        return MessageFormat.format(msgValue, args);
    }

    protected void addInformationMessage(String message, Object... args) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, getMessage(context, message, args), null));
    }

    protected void addWarningMessage(String message, Object... args) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, getMessage(context, message, args), null));
    }

    protected void addErrorMessage(String message, Object... args) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, getMessage(context, message, args), null));
    }

    protected String getParam(String param) {
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String, String> map = context.getExternalContext().getRequestParameterMap();
        return map.get(param);
    }

    protected Long getParamId(String param) {
        return Long.valueOf(getParam(param));
    }
}

src/main/java/org/agoncal/application/petstore/web/LocaleBean.java
package org.agoncal.application.petstore.web;

import org.agoncal.application.petstore.util.Loggable;

import javax.enterprise.context.SessionScoped;
import javax.enterprise.inject.Produces;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.io.Serializable;
import java.util.Locale;

@Named
@SessionScoped
@Loggable
public class LocaleBean implements Serializable {

    @Produces
    private Locale locale = FacesContext.getCurrentInstance().getViewRoot().getLocale();

    // ======================================
    // =          Business methods          =
    // ======================================

    public Locale getLocale() {
        return locale;
    }

    public String getLanguage() {
        return locale.getLanguage();
    }

    public void setLanguage(String language) {
        locale = new Locale(language);
        FacesContext.getCurrentInstance().getViewRoot().setLocale(locale);
    }
}

src/main/java/org/agoncal/application/petstore/web/ShoppingCartController.java
package org.agoncal.application.petstore.web;

import org.agoncal.application.petstore.domain.*;
import org.agoncal.application.petstore.service.CatalogService;
import org.agoncal.application.petstore.service.OrderService;
import org.agoncal.application.petstore.util.Loggable;

import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.enterprise.inject.Instance;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Antonio Goncalves
 *         http://www.antoniogoncalves.org
 *         --
 */

@Named
@ConversationScoped
@Loggable
@CatchException
public class ShoppingCartController extends Controller implements Serializable {

    // ======================================
    // =             Attributes             =
    // ======================================

    @Inject
    @LoggedIn
    private Instance<Customer> loggedInCustomer;
    @Inject
    private CatalogService catalogBean;
    @Inject
    private OrderService orderBean;
    @Inject
    private Conversation conversation;

    private List<CartItem> cartItems;
    private CreditCard creditCard = new CreditCard();
    private Order order;

    // ======================================
    // =              Public Methods        =
    // ======================================

    public String addItemToCart() {
        Item item = catalogBean.findItem(getParamId("itemId"));

        // Start conversation
        if (conversation.isTransient()) {
            cartItems = new ArrayList<CartItem>();
            conversation.begin();
        }

        boolean itemFound = false;
        for (CartItem cartItem : cartItems) {
            // If item already exists in the shopping cart we just change the quantity
            if (cartItem.getItem().equals(item)) {
                cartItem.setQuantity(cartItem.getQuantity() + 1);
                itemFound = true;
            }
        }
        if (!itemFound)
            // Otherwise it's added to the shopping cart
            cartItems.add(new CartItem(item, 1));

        return "showcart.faces";
    }

    public String removeItemFromCart() {
        Item item = catalogBean.findItem(getParamId("itemId"));

        for (CartItem cartItem : cartItems) {
            if (cartItem.getItem().equals(item)) {
                cartItems.remove(cartItem);
                return null;
            }
        }

        return null;
    }

    public String updateQuantity() {
        return null;
    }

    public String checkout() {
        return "confirmorder.faces";
    }

    public String confirmOrder() {
        order = orderBean.createOrder(getCustomer(), creditCard, getCartItems());
        cartItems.clear();

        // Stop conversation
        if (!conversation.isTransient()) {
            conversation.end();
        }

        return "orderconfirmed.faces";
    }

    public List<CartItem> getCartItems() {
        return cartItems;
    }

    public boolean shoppingCartIsEmpty() {
        return getCartItems() == null || getCartItems().size() == 0;
    }


    public Float getTotal() {

        if (cartItems == null || cartItems.isEmpty())
            return 0f;

        Float total = 0f;

        // Sum up the quantities
        for (CartItem cartItem : cartItems) {
            total += (cartItem.getSubTotal());
        }
        return total;
    }

    // ======================================
    // =         Getters & setters          =
    // ======================================

    public Customer getCustomer() {
        return loggedInCustomer.get();
    }


    public CreditCard getCreditCard() {
        return creditCard;
    }

    public void setCreditCard(CreditCard creditCard) {
        this.creditCard = creditCard;
    }

    public Order getOrder() {
        return order;
    }

    public void setOrder(Order order) {
        this.order = order;
    }

    public Conversation getConversation() {
        return conversation;
    }

    public CreditCardType[] getCreditCardTypes() {
        return CreditCardType.values();
    }
}

src/main/webapp/confirmorder.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                template="WEB-INF/layouts/template.xhtml">

    <ui:define name="title">#{i18n.orderConfirmed_yourOrderIsComplete}</ui:define>

    <ui:define name="body">

        <h2>#{i18n.orderConfirmed_yourOrderIsComplete}</h2>

        <h:form>

            <div>
                <legend>#{i18n.confirmorder_personalInformation}</legend>
                <h:panelGrid columns="3">
                    <h:outputText value="#{i18n.customer_firstname} :"/>
                    <h:inputText id="firstname" value="#{shoppingCartController.customer.firstname}" readonly="true"/>
                    <h:message for="firstname" style="color: red;"/>

                    <h:outputText value="#{i18n.customer_lastname} :"/>
                    <h:inputText id="lastname" value="#{shoppingCartController.customer.lastname}" readonly="true"/>
                    <h:message for="lastname" style="color: red;"/>

                    <h:outputText value="#{i18n.customer_email} :"/>
                    <h:inputText id="email" value="#{shoppingCartController.customer.email}" readonly="true"/>
                    <h:message for="email" style="color: red;"/>

                </h:panelGrid>
            </div>

            <div>
                <legend>#{i18n.confirmorder_deliveryAddress}</legend>
                <h:panelGrid columns="3">
                    <h:outputText value="*#{i18n.address_street1} :"/>
                    <h:inputText id="street1" value="#{shoppingCartController.customer.homeAddress.street1}"/>
                    <h:message for="street1" style="color: red;"/>

                    <h:outputText value="#{i18n.address_street2} :"/>
                    <h:inputText id="street2" value="#{shoppingCartController.customer.homeAddress.street2}"/>
                    <h:message for="street2" style="color: red;"/>

                    <h:outputText value="*#{i18n.address_city} :"/>
                    <h:inputText id="city" value="#{shoppingCartController.customer.homeAddress.city}"/>
                    <h:message for="city" style="color: red;"/>

                    <h:outputText value="#{i18n.address_state} :"/>
                    <h:inputText id="state" value="#{shoppingCartController.customer.homeAddress.state}"/>
                    <h:message for="state" style="color: red;"/>

                    <h:outputText value="*#{i18n.address_zipcode} :"/>
                    <h:inputText id="zipcode" value="#{shoppingCartController.customer.homeAddress.zipcode}"/>
                    <h:message for="zipcode" style="color: red;"/>

                    <h:outputText value="*#{i18n.address_country} :"/>
                    <h:inputText id="country" value="#{shoppingCartController.customer.homeAddress.country}"/>
                    <h:message for="country" style="color: red;"/>

                </h:panelGrid>
            </div>

            <div>
                <legend>#{i18n.creditCard}</legend>
                <h:panelGrid columns="3">
                    <h:outputText value="*#{i18n.creditCard_creditCardNumber} :"/>
                    <h:inputText id="creditCardNumber" value="#{shoppingCartController.creditCard.creditCardNumber}"/>
                    <h:message for="creditCardNumber" style="color: red;"/>

                    <h:outputText value="*#{i18n.creditCard_creditCardType} :"/>
                    <h:selectOneMenu value="#{shoppingCartController.creditCard.creditCardType}">
                        <f:selectItems value="#{shoppingCartController.creditCardTypes}"/>
                    </h:selectOneMenu>
                    <h:outputText value=""/>

                    <h:outputText value="*#{i18n.creditCard_creditCardExpDate} (MM/YY):"/>
                    <h:inputText id="creditCardExpDate" value="#{shoppingCartController.creditCard.creditCardExpDate}"/>
                    <h:message for="creditCardExpDate" style="color: red;"/>
                </h:panelGrid>
            </div>

            <div>
                <h:commandButton value="#{i18n.submit}" action="#{shoppingCartController.confirmOrder}" type="submit"/>
            </div>
        </h:form>

    </ui:define>
</ui:composition>

src/main/webapp/orderconfirmed.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                template="WEB-INF/layouts/template.xhtml">

    <ui:define name="title">#{i18n.orderConfirmed_yourOrderIsComplete}</ui:define>

    <ui:define name="body">

        <h2>#{i18n.orderConfirmed_yourOrderIsComplete}</h2>

        <h:form>
            <h:dataTable value="#{shoppingCartController.order.orderLines}" var="orderLine" styleClass="table">
                <h:column>
                    <strong><h:outputText value="#{orderLine.item.product.name}"/></strong>
                    <br/>
                    <h:outputText value="#{orderLine.item.name}"/>
                </h:column>
                <h:column>
                    <h:outputText value="#{orderLine.quantity}"/>
                </h:column>
                <h:column>
                    x
                    <h:outputText value="#{orderLine.item.unitCost}"/>
                    $
                </h:column>
                <h:column>
                    =
                    <h:outputText value="#{orderLine.subTotal}"/>
                    $
                </h:column>
            </h:dataTable>
            <br/>

            <div style="margin-top: 20px; font-weight: bold;">
                Total $ #{shoppingCartController.order.total}
            </div>
        </h:form>

        <legend>#{i18n.orderConfirmed_yourOrderIdIs} : #{shoppingCartController.order.id}</legend>

        <p style="margin-top: 15px">#{i18n.orderConfirmed_msg1}</p>

        <p style="margin-top: 15px">#{i18n.orderConfirmed_msg2}</p>

    </ui:define>
</ui:composition>

src/main/webapp/showcart.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                template="WEB-INF/layouts/template.xhtml">

    <ui:define name="title">#{i18n.shoppingCart}</ui:define>

    <ui:define name="body">

        <h2>#{i18n.shoppingCart}</h2>

        <!--Shopping Cart is empty-->
        <h:outputText value="#{i18n.shoppingCart_empty}" rendered="#{shoppingCartController.shoppingCartIsEmpty()}"/>

        <!--There are items in the Shopping Cart-->
        <h:form rendered="#{!shoppingCartController.shoppingCartIsEmpty()}">
            <h:dataTable value="#{shoppingCartController.cartItems}" var="oneItem" styleClass="table">
                <h:column>
                    <h:outputText value="#{oneItem.item.product.name}"/>
                    <br/>
                    <h:commandLink action="#{catalogController.doFindItem}">
                        <h:outputText value="#{oneItem.item.name}"/>
                        <f:param name="itemId" value="#{oneItem.item.id}"/>
                    </h:commandLink>
                </h:column>
                <h:column>
                    <h:commandLink action="#{shoppingCartController.updateQuantity}" styleClass="arrow_refresh">
                        <h:outputText value="#{i18n.update}"/>
                        <f:param name="itemId" value="#{oneItem.item.id}"/>
                    </h:commandLink>
                </h:column>
                <h:column>
                    <h:inputText value="#{oneItem.quantity}"/>
                </h:column>
                <h:column>
                    x
                    <h:outputText value="#{oneItem.item.unitCost}"/> $
                </h:column>
                <h:column>
                    = <h:outputText value="#{oneItem.subTotal}"/> $
                </h:column>
                <h:column>
                    &nbsp;
                    <h:commandLink action="#{shoppingCartController.removeItemFromCart}" styleClass="remove-from-cart">
                        <h:outputText value="#{i18n.remove}"/>
                        <f:param name="itemId" value="#{oneItem.item.id}"/>
                    </h:commandLink>
                </h:column>
            </h:dataTable>

            <br/>

            <div>
                Total $
                <h:outputText value="#{shoppingCartController.total}"/>
                &nbsp;
                <h:commandLink action="#{shoppingCartController.checkout}" value="Check Out"
                               styleClass="checkout-cart"/>
            </div>
        </h:form>

    </ui:define>
</ui:composition>

src/main/webapp/showitem.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                template="WEB-INF/layouts/template.xhtml">

    <f:metadata>
        <f:viewParam name="itemId" value="#{catalogController.itemId}" required="true"/>
        <f:event type="preRenderView" listener="#{catalogController.doFindItem()}"/>
    </f:metadata>

    <ui:define name="title">#{catalogController.item.product.name} - #{catalogController.item.name}</ui:define>

    <ui:define name="body">

        <h:outputText value="#{i18n.noItemsFound}" rendered="#{catalogController.item == null}"/>

        <h:form rendered="#{catalogController.item != null}">
            <div class="media">
                <h:graphicImage url="resources/images/#{catalogController.item.imagePath}"
                                alt="#{catalogController.item.name}" class="pull-left"/>

                <div class="media-body">
                    <h3 class="media-heading">#{catalogController.item.product.name} - #{catalogController.item.name}</h3>
                    <h4 class="media-heading">#{i18n.item_unitCost}: $#{catalogController.item.unitCost}</h4>
                    <h:outputText value="#{catalogController.item.description}"/>
                </div>
                <div class="pull-right">
                    <h:commandLink action="#{shoppingCartController.addItemToCart}" styleClass="add-to-cart"
                        rendered="#{accountController.loggedIn}">
                        <h:outputText value="#{i18n.searchResult_addToCart}"/>
                        <f:param name="itemId" value="#{catalogController.item.id}"/>
                    </h:commandLink>
                </div>
            </div>
        </h:form>

    </ui:define>
</ui:composition>

src/main/webapp/showitems.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                template="WEB-INF/layouts/template.xhtml">

    <f:metadata>
        <f:viewParam name="productId" value="#{catalogController.productId}" required="true"/>
        <f:event type="preRenderView" listener="#{catalogController.doFindItems()}"/>
    </f:metadata>

    <ui:define name="title">#{i18n.showItems_itemForProduct} : #{catalogController.product.name}</ui:define>

    <ui:define name="body">

        <h2>#{i18n.showItems_itemForProduct} : #{catalogController.product.name}</h2>

        <h:outputText value="#{i18n.noItemsFound}"
                      rendered="#{catalogController.items == null || catalogController.items.size() ==0}"/>

        <h:dataTable value="#{catalogController.items}" var="oneItem" rendered="#{catalogController.items.size() > 0}"
                     styleClass="table">
            <h:column>
                <div class="media">
                    <h:graphicImage url="resources/images/#{oneItem.imagePath}" alt="Item" class="pull-left"/>

                    <div class="media-body">
                        <h3 class="media-heading">
                            <h:link outcome="showitem" includeViewParams="true" value="#{oneItem.name}">
                                <f:param name="itemId" value="#{oneItem.id}"/>
                                <f:param name="cid" value="#{javax.enterprise.context.conversation.id}"/>
                            </h:link>
                        </h3>
                        <h4 class="media-heading">#{i18n.item_unitCost}: $#{oneItem.unitCost}</h4>
                        <h:outputText value="#{oneItem.description}"/>
                    </div>
                    <div class="pull-right">
                        <h:form>
                            <h:commandLink action="#{shoppingCartController.addItemToCart}" styleClass="add-to-cart"
                                           rendered="#{accountController.loggedIn}">
                                <h:outputText value="#{i18n.searchResult_addToCart}"/>
                                <f:param name="itemId" value="#{oneItem.id}"/>
                            </h:commandLink>
                        </h:form>
                    </div>
                </div>
            </h:column>
        </h:dataTable>

    </ui:define>
</ui:composition>